// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://biyfjdvneaycbhwodeaw.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpeWZqZHZuZWF5Y2Jod29kZWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA4MjIyMTgsImV4cCI6MjA0NjM5ODIxOH0.9cOIO0N02eji4hISFYmSXezer4CrsUMC90XzZ58lBzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);